[package]
name = "sov-eigenda-adapter"
description = "EigenDA adapter for Sovereign SDK rollups"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
alloy-consensus = { workspace = true, features = [
  "serde",
  "serde-bincode-compat",
  "k256",
] }
alloy-eips = { workspace = true }
alloy-network = { version = "1.0.37", default-features = false }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-rpc-types-eth = { version = "1.0.37", default-features = false }
alloy-serde = { workspace = true }
alloy-signer = { version = "1.0.37", default-features = false }
alloy-signer-local = { version = "1.0.37", default-features = false }
alloy-transport = { workspace = true }
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
async-trait = { workspace = true }
backon = { workspace = true, optional = true }
borsh = { workspace = true, features = ["bytes"] }
bytes = { workspace = true }
derive_more = { workspace = true }
eigenda-ethereum = { git = "https://github.com/diogofriggo/eigenda.git", branch = "master" }
eigenda-proxy = { git = "https://github.com/diogofriggo/eigenda.git", branch = "master", optional = true }
eigenda-verification = { git = "https://github.com/diogofriggo/eigenda.git", branch = "master" }
futures = { workspace = true }
hex = { workspace = true }
proptest = { workspace = true, features = ["alloc", "std"], optional = true }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.2", default-features = false, features = ["serde"] }
schemars = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
sov-rollup-interface = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"], optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "local-time",
] }
tracing-tree = { version = "0.4" }

[dev-dependencies]
alloy-consensus = { workspace = true, features = ["arbitrary"] }
alloy-provider = { workspace = true, features = ["anvil-api"] }
alloy-rpc-types = { workspace = true, features = ["anvil"] }
arbitrary = { workspace = true }
hex = { workspace = true }
jsonschema = { workspace = true }
rand = { workspace = true }
reltester = { workspace = true }
risc0-zkvm = { workspace = true, features = ["std"] }
test-strategy = { workspace = true }
testcontainers = { workspace = true }

[features]
arbitrary = ["dep:arbitrary", "dep:proptest"]
default = []
native = [
  "sov-rollup-interface/native",
  "alloy-eips/kzg",
  "dep:backon",
  "dep:tokio",
  "eigenda-ethereum/native",
  "dep:eigenda-proxy",
  "reth-trie-common/eip1186",
]
use-rbn-state = []
